ヘッダー・ハンバーガーメニュー・サイドメニュー・バックコンテンツの作成
shikosai32/shikosai.net pull request #11
Opened 2022-06-11 09:58 UTC by koutyuke

2022-06-11 12:41 UTC, Yusuke4869 requested changes

2022-06-11 12:41 UTC, Yusuke4869 commented on tailwind.config.js
> +        }
フォーマッターの対象じゃないので申し訳ないんだけど、
keyとvalueの間に空白を入れてほしい

2022-06-11 12:41 UTC, Yusuke4869 commented on src/components/Side.tsx
> +const Left: FC = () => <div />;
ここの用途を教えてください

2022-06-11 12:41 UTC, Yusuke4869 commented on src/components/BackContent.tsx
> +          <div className="py-14 ">
`py-14` の後に空白があります

`prettier-plugin-tailwindcss` というのがあるので、導入してみるといいかも
開発依存関係に追加後、`.prettierrc` に `"plugins": ["prettier-plugin-tailwindcss"]` を追加して使えます

2022-06-11 12:41 UTC, Yusuke4869 commented on src/components/Layout.tsx
> +import BackContent from "./BackContent";
```diff
- ./BackContent
+ BackContent
```

2022-06-11 12:49 UTC, koutyuke commented on src/components/Side.tsx
> +const Left: FC = () => <div />;
デザイン変更時用

2022-06-11 12:50 UTC, Yusuke4869 commented on src/components/Side.tsx
> +const Left: FC = () => <div />;
ok

2022-06-11 13:11 UTC, koutyuke commented on tailwind.config.js
> +        }
[2f9c7d4](https://github.com/shikosai32/shikosai.net/pull/11/commits/2f9c7d414b27a10d078cd495fa6fe249b4a91c0e)
[8d4ff79](https://github.com/shikosai32/shikosai.net/pull/11/commits/8d4ff797a6063b7656626dce07ebe693fd11d0a3)

2022-06-11 13:13 UTC, koutyuke commented on tailwind.config.js
> +        }
[2f9c7d4](https://github.com/shikosai32/shikosai.net/pull/11/commits/2f9c7d414b27a10d078cd495fa6fe249b4a91c0e)
[8d4ff79](https://github.com/shikosai32/shikosai.net/pull/11/commits/8d4ff797a6063b7656626dce07ebe693fd11d0a3)

2022-06-11 13:14 UTC, koutyuke commented on src/components/Layout.tsx
> +import BackContent from "./BackContent";
[bfb5d5d](https://github.com/shikosai32/shikosai.net/pull/11/commits/bfb5d5d8b2f1623737120bcc63b643faed19c31f)

2022-06-11 13:15 UTC, koutyuke commented on src/components/BackContent.tsx
> +          <div className="py-14 ">
[1802011](https://github.com/shikosai32/shikosai.net/pull/11/commits/1802011ce09af9e76a4ba05a799efceceadb2abc)
[8d4ff79](https://github.com/shikosai32/shikosai.net/pull/11/commits/8d4ff797a6063b7656626dce07ebe693fd11d0a3)

2022-06-11 13:24 UTC, Yusuke4869 approved these changes
あっｐろゔぇ

2022-06-13 11:30 UTC, dino3616 approved these changes

2022-06-15 05:14 UTC, sayoi341 approved these changes
あっpろゔぇ

2022-06-15 05:14 UTC, merged