Layout & index
shikosai32/shikosai.net pull request #15
Opened 2022-08-03 07:43 UTC by koutyuke

2022-08-03 10:00 UTC, dino3616 approved these changes

2022-08-04 12:37 UTC, dino3616 commented
- #14 

上ってこのPRで解決済み？

2022-08-04 12:39 UTC, koutyuke commented
そうだね
面倒だったから上げた

2022-08-04 12:48 UTC, Yusuke4869 commented
やったことをissueと紐づけて下さい

2022-08-04 12:56 UTC, koutyuke commented
紐づけたでぇ

2022-09-10 22:58 UTC, Yusuke4869 requested changes

2022-09-10 22:58 UTC, Yusuke4869 commented on src/components/Header.tsx
> +        <a href="./access" rel="noopener noreferrer" className="font-semibold">
Linkタグを使ってください

2022-09-10 22:58 UTC, Yusuke4869 commented on src/components/Header.tsx
> +        <a href="./circle" rel="noopener noreferrer" className="font-semibold">
ここも

2022-09-10 22:58 UTC, Yusuke4869 commented on src/components/Header.tsx
> +        <a href="./timetable" rel="noopener noreferrer" className="font-semibold">
ここも

2022-09-10 22:58 UTC, Yusuke4869 commented on src/components/Header.tsx
> +        <a href="./staff" rel="noopener noreferrer" className="font-semibold">
ここも

2022-09-10 22:58 UTC, Yusuke4869 commented on src/components/Header.tsx
>          <a href="./" rel="noopener noreferrer" className="flex items-center space-x-2">
ここも

2022-10-02 04:34 UTC, koutyuke commented on src/components/Header.tsx
>          <a href="./" rel="noopener noreferrer" className="flex items-center space-x-2">
[🔧(Fix): replace next/link](https://github.com/shikosai32/shikosai.net/pull/15/commits/de0a99bb3b991e108ee5a28e0e1f541fe710846b)

2022-10-02 04:34 UTC, koutyuke commented on src/components/Header.tsx
> +        <a href="./staff" rel="noopener noreferrer" className="font-semibold">
[🔧(Fix): replace next/link](https://github.com/shikosai32/shikosai.net/pull/15/commits/de0a99bb3b991e108ee5a28e0e1f541fe710846b)

2022-10-02 04:34 UTC, koutyuke commented on src/components/Header.tsx
> +        <a href="./timetable" rel="noopener noreferrer" className="font-semibold">
[🔧(Fix): replace next/link](https://github.com/shikosai32/shikosai.net/pull/15/commits/de0a99bb3b991e108ee5a28e0e1f541fe710846b)

2022-10-02 04:34 UTC, koutyuke commented on src/components/Header.tsx
> +        <a href="./circle" rel="noopener noreferrer" className="font-semibold">
[🔧(Fix): replace next/link](https://github.com/shikosai32/shikosai.net/pull/15/commits/de0a99bb3b991e108ee5a28e0e1f541fe710846b)

2022-10-02 04:34 UTC, koutyuke commented on src/components/Header.tsx
> +        <a href="./access" rel="noopener noreferrer" className="font-semibold">
[🔧(Fix): replace next/link](https://github.com/shikosai32/shikosai.net/pull/15/commits/de0a99bb3b991e108ee5a28e0e1f541fe710846b)

2022-10-02 04:48 UTC, Yusuke4869 requested changes

2022-10-02 04:48 UTC, Yusuke4869 commented on src/components/Header.tsx
> +        <Link href="./circle">
```diff
- ./circle
+ /circle
```

2022-10-02 05:40 UTC, dino3616 submitted a review, later dismissed

2022-10-02 07:06 UTC, Yusuke4869 approved these changes

2022-10-02 07:07 UTC, dino3616 approved these changes

2022-10-02 07:10 UTC, closed without merging