AccessPage
shikosai32/shikosai.net pull request #55
Opened 2022-10-01 16:59 UTC by ituki0426

2022-10-02 07:28 UTC, Yusuke4869 approved these changes

2022-10-02 07:36 UTC, Yusuke4869 submitted a review, later dismissed

2022-10-02 07:41 UTC, dino3616 requested changes
全体で使われているフォントが違うような？
~~`Montserrat`っていうのが使われているっぽいです。~~
~~デザインをNotoに修正します。~~
`Noto Serif JP`に修正したので、実装も修正お願い。

2022-10-02 07:41 UTC, dino3616 commented on src/pages/access.tsx
> +          className="h-[300px] w-[100%] md:h-[500px]"
スマホの表示はこれでいいんだけど、PC or タブレットだと大きすぎる気がするのでもうちょい小さく

2022-10-02 07:41 UTC, dino3616 commented on src/pages/access.tsx
> +      <div className="text-4xl md:text-6xl">- ADDRESS -</div>
流石に`6xl`は大きいかな。
あとデザイン上は`semi-bold`付いてるっぽいです。

2022-10-02 07:41 UTC, dino3616 commented on src/pages/access.tsx
> +      <div className="mt-5 text-2xl md:text-3xl">〒312-8508</div>
TELまで同じ`<div>`の同じスタイルでいけるはず。
デザイン上は大きさも太さも同じです。

2022-10-09 14:04 UTC, dino3616 submitted a review, later dismissed

2022-10-09 14:51 UTC, Yusuke4869 approved these changes

2022-10-09 15:00 UTC, merged