Feat: timetable
shikosai32/shikosai.net pull request #57
Opened 2022-10-02 06:54 UTC by Yusuke4869

Close #46

2022-10-08 10:58 UTC, dino3616 requested changes
このページのフォントは全部`Roboto Serif`です。
あとセレクタのスタイルをもうちょいデザインによせてください。

実装方法に関しては他の方に任せるます。
(今回は突貫工事なので自分はこの実装でいいと思うます)

2022-10-08 10:58 UTC, dino3616 commented on src/pages/timetable.tsx
> +              key={i}
うーんこの...。
`data.day*`に`id`フィールド作ってそれを入れたい...。

2022-10-08 10:58 UTC, dino3616 commented on src/components/timetable/TableItem.tsx
> +        {start} ~ {end}
コンテンツの高さに拘わらず、時間は右下に来るようにしてください。

2022-10-08 10:58 UTC, dino3616 commented on src/components/timetable/TableItem.tsx
> +      className="mb-2 rounded-lg bg-stone-600 p-4"
背景色は`bg-white`です。
`rounded`はもうちょいほしいです。

2022-10-08 10:58 UTC, dino3616 commented on src/components/timetable/TableItem.tsx
> +        {start} ~ {end}
あと文字色はちょい灰色の`#707070`です。

2022-10-08 10:58 UTC, dino3616 commented on src/pages/timetable.tsx
> +          <span className="mb-1 md:text-2xl lg:text-4xl">For</span>
lower caseです。

2022-10-08 10:59 UTC, Yusuke4869 commented on src/pages/timetable.tsx
> +              key={i}
めんどくさいです

2022-10-08 11:01 UTC, dino3616 commented on src/pages/timetable.tsx
> +              key={i}
:kusa:
じゃぁどうせ静的サイトだから配列は動的に変わらないという理由であｐｐろヴぇです。

2022-10-09 13:58 UTC, dino3616 approved these changes
セレクタのスタイルを今すぐ片づけるのは難しいとのことなので、それ以外はあｐｐろヴぇです。

2022-10-09 14:49 UTC, merged