feat: ✨ LPを作成
shikosai32/shikosai.net pull request #58
Opened 2022-10-02 18:59 UTC by dino3616

## Related Issues

- close #18

2022-10-02 23:58 UTC, dino3616 commented
あーTODO残ってるのでやっぱりまだready for reviewですね。

2022-10-03 14:22 UTC, Yusuke4869 requested changes

2022-10-03 14:22 UTC, Yusuke4869 commented on src/components/index/Caution.tsx
> +          第32回茨香祭では、新型コロナウイルス感染症対策のために、いくつかの注意事項がございます。何卒、ご了承願います。
```diff
- 第32回茨香祭では、新型コロナウイルス感染症対策のために、いくつかの注意事項がございます。
+ 第32回茨香祭では新型コロナウイルス感染症対策のため、注意事項がございます。
```

改行して以下の変更
```diff
- 何卒、ご了承願います。
+ ご理解とご協力のほどお願い申し上げます。
```

2022-10-03 14:22 UTC, Yusuke4869 commented on src/pages/index.tsx
>      <Layout PageTitle="Hello World">
shikosai32 にタイトルを変更

2022-10-03 18:35 UTC, dino3616 commented on src/components/index/Caution.tsx
> +          第32回茨香祭では、新型コロナウイルス感染症対策のために、いくつかの注意事項がございます。何卒、ご了承願います。
fixed: https://github.com/shikosai32/shikosai.net/pull/58/commits/4be74857211a4d31b4a773d3440423434b6b6b64

2022-10-09 15:15 UTC, dino3616 commented
```
下記の件ですが、駐車場の文章に以下を追加してください。

・近隣の店舗駐車場への駐車、路上駐車は大変迷惑となりますので、絶対におやめください。

 

また、これらの注意事項は、フォームに記入されていましたが、HPのTOPページの

注意事項にも体裁を整えて記載してください。（これから書くのかもしれませんが）

 

また、HP自体は不完全なところは公開しないで、できている部分は公開してもいいと思います。

（公開するときは連絡ください。来週始めには公開できるといいと思います）
```

2022-10-09 15:16 UTC, dino3616 commented
```
続けてで申し訳ありませんが、TOPページの注意事項に追加で

 

・駐車場の台数に限りがございますので、公共交通機関をご利用の上お越しください。

 

・お申込多数となった場合、申込受付を終了する場合がございます。

　(入場予約の文章に追加するといいと思います)

 

を入れてください。
```

2022-10-09 15:16 UTC, dino3616 commented
```
TOPページの注意事項ですが、

・第32回茨香祭は2日間に渡って開催されますが、一般の方のご入場は1日目のみとさせて頂いております。

とありますが、一般で入場できるのは、在校生の保護者と県内小中学生と保護者のみなので、

・第32回茨香祭は2日間に渡って開催されますが、一般の方につきましては、在校生の保護者と県内小中学生・保護者のみ、また、ご入場は1日目のみとさせて頂いております。

のような感じに変更してください。

 

よろしくお願いします。
```

2022-10-09 23:14 UTC, Yusuke4869 approved these changes

2022-10-09 23:15 UTC, merged